services:

  postgres:
    restart: always
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_DB=trading
      - POSTGRES_PASSWORD=toughgraff
    volumes:
      - ./modules/core/src/main/resources/tables.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5