object Versions {
  val catsVersion           = "2.6.1"
  val catsEffectVersion     = "3.4.8"
  val scalaVersion          = "3.2.2"
  val log4j2Version         = "2.13.1"
  val logbackVersion        = "1.2.6"
  val squantsVersion        = "1.8.3"
  val circeVersion          = "0.14.1"
  val monocleVersion        = "3.1.0"
  val skunkVersion          = "0.5.1"
  val zioVersion            = "2.0.15"
  val zioPreludeVersion     = "1.0.0-RC19"
  val zioInteropCatsVersion = "23.0.0.8"
  val zioConfigVersion      = "4.0.0-RC16"
  val zioLoggingVersion     = "2.1.11"
  val quickLensVersion      = "1.9.2"
  val zioJsonVersion        = "0.6.0"
  val sttpZioJsonVersion    = "3.8.15"
  val flywayDbVersion       = "9.1.6"
  val kantanCsvVersion      = "0.7.0"
  val tapirVersion          = "1.3.0"
}
